POST http://localhost:3000/api/v1/goals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJraGFsaWQiLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTIyVDE0OjU5OjE4LjgyMTE5MTU3MiswMzowMCIsImV4cGlyZWRfYXQiOiIyMDI0LTAxLTIzVDE0OjU5OjE4LjgyMTE5MTY4NyswMzowMCJ9.lzeqLbuehOIERbLiBgebZUkBHBrlRqGPqlLiINk8MzA

{
  "name": "Running every day",
  "description": "Every day i must run for 30 minutes",
  "start_date": "2023-01-01T15:04:05Z",
  "target_date": "2030-01-01T15:04:05Z"
}