POST http://localhost:3000/api/v1/goals/1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJraGFsaWQiLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTIwVDE2OjI5OjI3Ljg1NTA2NTY1MiswMzowMCIsImV4cGlyZWRfYXQiOiIyMDI0LTAxLTIxVDE2OjI5OjI3Ljg1NTA2NTc0NCswMzowMCJ9.47QbFn0wd7y0JnteglMtZwaaLioHArSjA_XLYLAZQa0

{
  "name": "Wake up early every morning",
  "description": "To run every day you must wake up early every morning",
  "frequency": "Daily"
}