DELETE http://localhost:3000/api/v1/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJraGFsaWQiLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTE1VDIzOjUwOjE5Ljk2NDk4NjczMyswMzowMCIsImV4cGlyZWRfYXQiOiIyMDI0LTAxLTE2VDIzOjUwOjE5Ljk2NDk4NjgzMSswMzowMCJ9.oVh_htDcuKi46T4s0Y5SXi76uQzQ8INeUjYeSVtK3bM