POST https://localhost/api/v1/goals/1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJraGFsaWQiLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTIwVDAwOjE4OjM4LjQwMTk1NjM5MloiLCJleHBpcmVkX2F0IjoiMjAyNC0wMS0yMVQwMDoxODozOC40MDE5NTY0OTVaIn0.N2tVGgGWmg0rSByDTGOPkB9kUqIRNdisJ0hIjVj92oE

{
  "name": "Wake up early every morning",
  "description": "To run every day you must wake up early every morning",
  "frequency": "Daily"
}