POST https://localhost/api/v1/goals/1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJraGFsaWQiLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTIwVDEzOjE0OjU3LjQyMjg2MzY3WiIsImV4cGlyZWRfYXQiOiIyMDI0LTAxLTIxVDEzOjE0OjU3LjQyMjg2Mzc3MloifQ.4qLYJ5FZZfMkzU8lA_S-h6UJ1v2B2gEE_f78Nv99MBA

{
  "name": "Wake up early every morning",
  "description": "To run every day you must wake up early every morning",
  "frequency": "Daily"
}