DELETE https://localhost/api/v1/goals/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJraGFsaWQiLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTE2VDAwOjE4OjAwLjQwODAyOTE4NyswMzowMCIsImV4cGlyZWRfYXQiOiIyMDI0LTAxLTE3VDAwOjE4OjAwLjQwODAyOTI4NCswMzowMCJ9.98psk6RogNg0I_VKdB2Xnv-_RitsuM9EgBnCMxzLfac