GET http://localhost:3000/api/v1/goals?page_id=1&page_size=5
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzdHJpbmciLCJpc3N1ZWRfYXQiOiIyMDI0LTAxLTI0VDE5OjM5OjI3Ljk0MTM1NzMzNSswMzowMCIsImV4cGlyZWRfYXQiOiIyMDI0LTAxLTI1VDE5OjM5OjI3Ljk0MTM1NzQzNSswMzowMCJ9.fCwys7rahN2CT9Y9ZQ3bKKxU1Td6boN2zK5FJMRoBQs