name: Build and Test

on:
  push:
    branches:
      - lab_09
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Install Dependencies
        run: |
          cd ./src/
          go mod download

      - name: Test
        run: |
          cd ./src/
          go test ./...

      - name: Build
        run: |
          cd ./src/
          go build -o ./server ./cmd/web/main.go
